const cartasTipo5 = [
    { tipo: 5, pontos: -1, fakeNews: "Você compartilhou no grupo a notícia inofensiva de que o Senac cancelou as aulas para criar um Metaverso, gerando apenas confusão temporária." },
    { tipo: 5, pontos: -5, fakeNews: "Você compartilhou um link falso prometendo ferramentas pagas de graça, o que instalou um ransomware e criptografou o projeto inteiro da equipe." },
    { tipo: 5, pontos: -5, fakeNews: "Você espalhou um boato sobre um colega de sala usando um vídeo manipulado (deepfake), ferindo a ética gravemente e configurando cyberbullying." },
    { tipo: 5, pontos: -2, fakeNews: "Você repassou a corrente de que o ChatGPT foi adquirido pelo Governo Federal e passará a cobrar impostos por mensagem." },
    { tipo: 5, pontos: -5, fakeNews: "Você vazou acidentalmente dados reais de clientes em um fórum público ao tentar tirar uma dúvida técnica de banco de dados, violando gravemente a LGPD." },
    { tipo: 5, pontos: -1, fakeNews: "Você enviou em todos os grupos que carregar o celular dentro do micro-ondas carrega a bateria em 5 segundos, uma desinformação facilmente desmentida." },
    { tipo: 5, pontos: -4, fakeNews: "Você clicou de forma apressada em um e-mail de phishing disfarçado de 'Vaga de Emprego Urgente' e comprometeu suas senhas do sistema." },
    { tipo: 5, pontos: -3, fakeNews: "Você alertou seus amigos de que a vacina atualiza um chip 5G direto no seu DNA sem checar a confiabilidade científica da fonte." },
    { tipo: 5, pontos: -3, fakeNews: "Você acessou a nuvem da empresa em um Wi-Fi público de praça sem usar VPN, teve sua sessão interceptada e ignorou as boas práticas." },
    { tipo: 5, pontos: -2, fakeNews: "Você compartilhou a notícia de que alterar o arquivo 'hosts' do Windows magicamente deixa a internet 1000% mais rápida, demonstrando falta de senso crítico." },
    { tipo: 5, pontos: -4, fakeNews: "Você aceitou o pedido de conexão de um falso recrutador no LinkedIn e forneceu informações sensíveis da topologia de rede do seu projeto." },
    { tipo: 5, pontos: -3, fakeNews: "Você espalhou no grupo um print falsificado dizendo que o Projeto Integrador foi cancelado, gerando pânico e prejudicando o cronograma da turma." },
    { tipo: 5, pontos: -5, fakeNews: "Você copiou um código de um repositório fechado, sem dar os créditos, e entregou no seu trabalho afirmando ser 100% autoral (Plágio)." },
    { tipo: 5, pontos: -4, fakeNews: "Você acreditou em um e-mail falso de 'Verificação de Segurança' e digitou seu código de Autenticação de 2 Fatores (2FA) em uma página clonada." },
    { tipo: 5, pontos: -3, fakeNews: "Você utilizou estatísticas geradas por IA no seu projeto sem checar a fonte, descobrindo na hora da apresentação que a IA havia alucinado os números." },
    { tipo: 5, pontos: -5, fakeNews: "Você presenciou colegas humilhando um aluno novo em um servidor acadêmico e curtiu a mensagem, falhando gravemente no papel de espectador ativo." },
    { tipo: 5, pontos: -3, fakeNews: "Você instalou um app não oficial que prometia 'Ver quem visitou seu perfil' e acabou concedendo acesso indevido a todos os seus contatos." },
    { tipo: 5, pontos: -5, fakeNews: "Você baixou uma versão 'crackeada' de um software de edição recomendado por um influenciador e infectou os computadores do laboratório." },
    { tipo: 5, pontos: -3, fakeNews: "Você recebeu uma mensagem no WhatsApp clonado de um colega pedindo PIX urgente para pagar o servidor do projeto e transferiu sem ligar para confirmar." },
    { tipo: 5, pontos: -4, fakeNews: "Você comprou uma câmera IoT super barata da internet sem ler os termos e configurou na rede principal, criando uma brecha de segurança enorme." }
];