const cartasTipo2 = [
    { tipo: 2, pontos: 2, cenario: "Os alunos usam vídeos apenas para ver a sintaxe correta de uma query SQL. Isso é exemplo de:", alternativas: [ {texto: "Educação Midiática Avançada.", correta: false}, {texto: "Mídia como recurso (Uso e análise técnica).", correta: true}, {texto: "Fluência cidadã.", correta: false} ], base: "Mídia como recurso foca no conteúdo. O uso é pontual e instrumental, limitado a atividades específicas." },
    { tipo: 2, pontos: 4, cenario: "Você propõe: 'Investiguem como a profissão de TI é estereotipada nas séries de TV e o impacto disso no mercado'. Essa prática é:", alternativas: [ {texto: "Mídia como recurso de ilustrativo.", correta: false}, {texto: "Educação Midiática (Investigação crítica).", correta: true}, {texto: "Letramento apenas tecnológico.", correta: false} ], base: "Educação midiática foca na investigação crítica e contextualizada: como o tópico é representado e quais interesses estão em disputa." },
    { tipo: 2, pontos: 3, cenario: "Quando a mídia é o 'meio' para transmitir a matéria escolar, estamos falando de:", alternativas: [ {texto: "Mídia como recurso pedagógico.", correta: true}, {texto: "Educação Midiática.", correta: false}, {texto: "Comunicação Transversal.", correta: false} ], base: "Mídia como recurso: Considerar a tecnologia e a mídia como instrumentos técnicos para facilitar a transmissão do conhecimento." },
    { tipo: 2, pontos: 5, cenario: "A turma produz um podcast para refutar narrativas falsas sobre segurança em nuvem. Qual a abordagem?", alternativas: [ {texto: "Mídia como recurso didático passivo.", correta: false}, {texto: "Educação midiática (Criação reflexiva).", correta: true}, {texto: "Substituição do currículo.", correta: false} ], base: "Educação midiática: Criação reflexiva de mídias. Os alunos produzem um conteúdo para validar ou refutar narrativas, refletindo sua intencionalidade." },
    { tipo: 2, pontos: 2, cenario: "Se o objetivo do professor é primariamente a eficácia na transmissão do conteúdo do manual técnico, ele está usando a mídia como:", alternativas: [ {texto: "Objeto de estudo.", correta: false}, {texto: "Recurso pedagógico.", correta: true}, {texto: "Ferramenta de subversão.", correta: false} ], base: "Mídia como recurso pedagógico: Buscar primordialmente a eficácia na transmissão do conteúdo curricular." },
    { tipo: 2, pontos: 4, cenario: "Educação midiática exige que a reflexão integre o currículo de qual forma?", alternativas: [ {texto: "Como disciplina isolada e optativa.", correta: false}, {texto: "Como uma camada transversal e contínua.", correta: true}, {texto: "Somente nas aulas de informática básica.", correta: false} ], base: "Educação midiática: A abordagem é transversal e contínua, como uma camada que integra a reflexão midiática em todo o currículo." },
    { tipo: 2, pontos: 3, cenario: "Reproduzir na sala um vídeo famoso do TikTok sem questionar quem financiou o criador é um sinal de:", alternativas: [ {texto: "Educação Midiática plena.", correta: false}, {texto: "Mídia como recurso sem letramento informacional.", correta: true}, {texto: "Competência Multimodal.", correta: false} ], base: "Usar mídias sem refletir sobre os processos de acesso, construção e difusão da mensagem é tratá-las como meios para aprender outras coisas, não como educação midiática." },
    { tipo: 2, pontos: 5, cenario: "Orientar o aluno a checar o autor de um artigo da Wikipedia sobre redes antes de utilizá-lo é uma transição para:", alternativas: [ {texto: "O ensino conteudista.", correta: false}, {texto: "A educação midiática focada em credibilidade.", correta: true}, {texto: "A censura digital.", correta: false} ], base: "Educação midiática estimula a reflexão sobre a origem e a confiabilidade dos conteúdos midiáticos acessados." },
    { tipo: 2, pontos: 3, cenario: "Na Educação Midiática, criar uma mídia (como um relatório) exige reflexão sobre:", alternativas: [ {texto: "Implicações éticas, escolhas e responsabilidade enquanto autor.", correta: true}, {texto: "Apenas as margens e a fonte do documento.", correta: false}, {texto: "Quantas visualizações o material terá.", correta: false} ], base: "Educação midiática: Incentivar a expressão... refletindo sobre as responsabilidades e escolhas enquanto autor." },
    { tipo: 2, pontos: 4, cenario: "Analisar como algoritmos direcionam ofertas de cursos de TI e debater isso na sala de aula é um exemplo claro de:", alternativas: [ {texto: "Uso instrumental da tecnologia.", correta: false}, {texto: "Educação midiática na cultura digital.", correta: true}, {texto: "Mídia como recurso ilustrativo.", correta: false} ], base: "Educação midiática: Refletir sobre as implicações éticas, sociais e políticas das mídias, incluindo o funcionamento de algoritmos." },
    // Para completar 20, replicarei lógicas estruturais que validam o limite
    { tipo: 2, pontos: 2, cenario: "Mostrar um documentário sem debater as vozes omitidas pelo diretor caracteriza:", alternativas: [{texto:"Educação Midiática.", correta: false}, {texto:"Mídia como recurso técnico.", correta: true}, {texto:"Cidadania digital.", correta: false}], base: "Mídia como recurso: A mídia é um meio para ilustrar, o uso é instrumental." },
    { tipo: 2, pontos: 3, cenario: "A diferença central é que a Educação Midiática considera a mídia como:", alternativas: [{texto:"Objeto de estudo e ambiente de prática da cidadania.", correta: true}, {texto:"Ferramenta de apoio passivo.", correta: false}, {texto:"Conteúdo extra.", correta: false}], base: "Educação Midiática: A mídia é o objeto de estudo e o ambiente de prática da cidadania." },
    { tipo: 2, pontos: 4, cenario: "Quando os alunos usam ferramentas de verificação para analisar a origem de uma fonte, estão focados na:", alternativas: [{texto:"Educação Midiática.", correta: true}, {texto:"Eficiência do recurso.", correta: false}, {texto:"Instrumentalização.", correta: false}], base: "Seleção, avaliação e debate crítico: usar ferramentas de verificação." },
    { tipo: 2, pontos: 1, cenario: "Utilizar uma animação apenas para manter a turma quieta e ilustrar um tema é:", alternativas: [{texto:"Transversalidade.", correta: false}, {texto:"Mídia como recurso.", correta: true}, {texto:"Intencionalidade.", correta: false}], base: "Mídia como recurso: tornar o aprendizado mais próximo da realidade de forma pontual." },
    { tipo: 2, pontos: 5, cenario: "Questionar o impacto social da difusão de um meme corporativo na aula é atitude de:", alternativas: [{texto:"Gestão de TI.", correta: false}, {texto:"Educação Midiática.", correta: true}, {texto:"Uso como recurso.", correta: false}], base: "Debatendo sobre credibilidade, viés, propósito e impacto social." },
    { tipo: 2, pontos: 2, cenario: "Fazer uma reprodução prática para consolidar o conhecimento sem questionar a mídia original:", alternativas: [{texto:"É Educação Midiática ideal.", correta: false}, {texto:"É focar no conteúdo (Mídia como recurso).", correta: true}, {texto:"Desenvolve autoria crítica.", correta: false}], base: "Reprodução prática para consolidar conhecimento caracteriza Mídia como Recurso." },
    { tipo: 2, pontos: 3, cenario: "Incentivar a reproduzir formatos de mídias sociais apenas para ser 'descolado' reflete:", alternativas: [{texto:"Cidadania ativa.", correta: false}, {texto:"Mídia como recurso (sem reflexão).", correta: true}, {texto:"Criação reflexiva.", correta: false}], base: "Mídia como recurso: Incentivar a expressão para reproduzir formatos e tendências." },
    { tipo: 2, pontos: 4, cenario: "Refletir sobre o viés do formador de opinião em um canal de programação do YouTube:", alternativas: [{texto:"Mídia como objeto de reflexão midiática.", correta: true}, {texto:"Mídia como recurso didático.", correta: false}, {texto:"Letramento instrumental.", correta: false}], base: "Investigar como o tema é representado e os interesses em disputa." },
    { tipo: 2, pontos: 5, cenario: "Identificar a intencionalidade de um artigo que defende o fim do trabalho remoto:", alternativas: [{texto:"Mídia como recurso.", correta: false}, {texto:"Educação Midiática.", correta: true}, {texto:"Autoexpressão.", correta: false}], base: "Desenvolver a capacidade de análise crítica (intencionalidade, autoria) de toda mensagem." },
    { tipo: 2, pontos: 2, cenario: "Baixar e ler um PDF apenas para a prova de infraestrutura:", alternativas: [{texto:"Educação midiática transversal.", correta: false}, {texto:"Busca focada no conteúdo (Mídia recurso).", correta: true}, {texto:"Competência multimodal.", correta: false}], base: "Busca focada em identificar fatos e informações principais sobre o tema." }
];