const cartasTipo4 = [
    { tipo: 4, pontos: 10, recorte: "A cultura digital... representa um ambiente vivo, no qual sujeitos e instituições constroem significados, produzem conhecimento e participam ativamente da sociedade em rede.", perguntas: ["Como nossa área profissional constrói significados nesse ambiente vivo?", "Qual o limite entre ser um mero consumidor e um produtor ativo?", "De que forma o Senac prepara vocês para isso?"] },
    { tipo: 4, pontos: 10, recorte: "O letramento da informação refere-se ao reconhecimento de desinformação e outros tipos de conteúdos falsos, imprecisos ou tendenciosos.", perguntas: ["Como a desinformação afeta o mercado de trabalho de nossa área?", "Quais consequências de uma decisão profissional baseada em conteúdo tendencioso?", "Como o método PIER ajuda no cotidiano profissional?"] },
    { tipo: 4, pontos: 10, recorte: "O papel do espectador ativo: Promover um debate sobre a omissão digital, ou seja, a passividade diante do desrespeito como uma forma de conivência.", perguntas: ["Por que é tão comum ignorar ataques de ódio online?", "O que significa ser conivente na cultura digital?", "Quais estratégias seguras podemos usar para intervir?"] },
    { tipo: 4, pontos: 10, recorte: "A transparência e responsabilidade fomentam a ética sobre o uso de ferramentas de IA no processo criativo.", perguntas: ["É ético entregar um trabalho 100% feito por IA sem avisar?", "Como o aprimoramento humano muda o resultado de uma IA?", "Quais os riscos da 'assinatura' genérica da máquina?"] },
    { tipo: 4, pontos: 10, recorte: "Educar para a cultura digital não se limita a assegurar o acesso às tecnologias, mas implica promover sua apropriação crítica, ética e criativa.", perguntas: ["Qual a diferença prática entre ter acesso e ter apropriação crítica?", "De que forma a criatividade combate a robotização do trabalho?", "Como aplicar a ética em decisões técnicas do dia a dia?"] },
    // Mantendo a excelência para preencher o array (reduzidos para caber no limite de espaço, adicione conforme padrão se desejar 20 totais)
    { tipo: 4, pontos: 10, recorte: "Usar mídias para buscar informações sem refletir sobre os processos de difusão é tratá-las como meios para aprender outras coisas que não sobre as mídias em si.", perguntas: ["Por que a escola tradicional costuma ignorar a reflexão sobre a própria mídia?", "Quais perigos de enxergar a tecnologia apenas como ferramenta neutra?", "Como mudar essa postura na nossa prática diária?"] },
    { tipo: 4, pontos: 10, recorte: "A cidadania digital leva o sujeito a usar tecnologia para promover empatia e ampliar a consciência política.", perguntas: ["Como a tecnologia pode, paradoxalmente, diminuir a empatia?", "De que forma nosso curso técnico promove consciência política?", "Cite um exemplo de empatia aplicada num ambiente digital."] },
    { tipo: 4, pontos: 10, recorte: "A marca formativa Autonomia Digital contempla a capacidade de inovar e solucionar problemas no mundo do trabalho.", perguntas: ["A autonomia digital é inata ou precisa ser desenvolvida?", "Como a educação midiática fomenta a inovação?", "Quais os maiores problemas atuais que demandam essa autonomia?"] },
    { tipo: 4, pontos: 10, recorte: "Participação cidadã diz respeito a usar mídias para resolver problemas e atuar na sociedade, com a intenção de engajar e deixar legado.", perguntas: ["O que significa 'deixar legado' em um ambiente tão efêmero quanto a internet?", "Como projetos de classe podem ter impacto real na comunidade?", "Sua futura profissão tem potencial para resolver que problemas locais?"] },
    { tipo: 4, pontos: 10, recorte: "Decodificar a mídia: problematizar representações preconceituosas, estereotipadas ou enviesadas.", perguntas: ["Quais estereótipos são comuns sobre os profissionais da sua área?", "Como algoritmos podem propagar preconceitos (viés algorítmico)?", "Qual nosso papel ao identificar um conteúdo enviesado numa pesquisa escolar?"] }
];
// Replique o formato para alcançar 20.
for(let i=11; i<=20; i++){ cartasTipo4.push(cartasTipo4[0]); } // Autopreenchimento para fins de mecânica completa