const cartasTipo3 = [
    { tipo: 3, pontos: 3, cenario: "Ao ensinar configuração de arquivos como o lighttpd mime-type, o docente pede que os alunos verifiquem por que um fórum ensinou a sintaxe errada. Isso é:", alternativas: [ {texto: "Intencionalidade no planejamento de aulas.", correta: true}, {texto: "Perda de foco técnico.", correta: false}, {texto: "Abordagem conteudista.", correta: false} ], base: "Intencionalidade: estabelecer objetivos de educação midiática, refletindo sobre erros e confiabilidade, além dos objetivos curriculares." },
    { tipo: 3, pontos: 4, cenario: "O professor pede que a turma crie um 'Pacto de Comunidade' com regras inegociáveis para o grupo de WhatsApp da classe. O foco é:", alternativas: [ {texto: "Apoiar a infraestrutura técnica.", correta: false}, {texto: "Desenvolver cidadania digital e empatia online.", correta: true}, {texto: "Censurar o debate.", correta: false} ], base: "Atividade prática docente: desenvolver um 'Pacto de Comunidade' com regras inegociáveis para a convivência online respeitosa." },
    { tipo: 3, pontos: 5, cenario: "Antes de criar um projeto (como a plataforma EduForge), o docente orienta as fases de ativação (leitura), imersão e pré-produção. Essa prática estrutura a:", alternativas: [ {texto: "Autoexpressão responsável.", correta: true}, {texto: "Busca de informações apenas.", correta: false}, {texto: "Leitura passiva.", correta: false} ], base: "Acompanhar o processo de produção, incentivando-os a planejá-lo antes da criação. Etapas: Ativação, Imersão, Pré-produção, Produção." },
    { tipo: 3, pontos: 2, cenario: "Em vez de apenas entregar a nota, o professor faz os alunos refletirem: 'Quem se beneficia com essa fake news que analisamos?'. Ele está aplicando a:", alternativas: [ {texto: "Avaliação técnica.", correta: false}, {texto: "Análise crítica de impacto.", correta: true}, {texto: "Revisão ortográfica.", correta: false} ], base: "Refletindo sobre a criação de mídias (Impacto): Quem pode se beneficiar ou ser prejudicado por essa mensagem?" },
    { tipo: 3, pontos: 4, cenario: "Como docente, você vincula a competência técnica de TI para resolver um problema social real na comunidade (Ex: um site para coleta seletiva). Isso estimula:", alternativas: [ {texto: "A Participação Cidadã e criação de legado.", correta: true}, {texto: "O consumismo digital.", correta: false}, {texto: "O isolamento acadêmico.", correta: false} ], base: "Encorajar a produção com intenção de resolver problemas reais, garantindo a participação cidadã ativa e construção de legado." },
    { tipo: 3, pontos: 3, cenario: "Aplicar o Checklist de Autoavaliação de Segurança (2FA, senhas) nas aulas práticas é estratégico para desenvolver:", alternativas: [ {texto: "Análise semiótica.", correta: false}, {texto: "Cidadania e segurança digital.", correta: true}, {texto: "Letramento informacional puro.", correta: false} ], base: "Cidadania digital: Orientar os estudantes a fortalecer sua privacidade e seguranças nesses espaços." },
    { tipo: 3, pontos: 4, cenario: "O docente avalia conteúdos gerados por IA com os alunos analisando 'Falta de sincronia', 'mãos estranhas' ou 'iluminação'. Ele trabalha o eixo de:", alternativas: [ {texto: "Observação crítica de mídias.", correta: true}, {texto: "Programação neurolinguística.", correta: false}, {texto: "Transparência.", correta: false} ], base: "Protocolo de IA (Observação): Examine atentamente a mensagem e procure falta de sincronia, aberrações em mãos, iluminação, etc." },
    { tipo: 3, pontos: 5, cenario: "Ao ensinar sobre o arquivo hosts em sistemas, o docente orienta investigar como malwares alteram esse arquivo para redirecionar dados (phishing). Isso vincula o técnico ao:", alternativas: [ {texto: "Letramento midiático e segurança informacional.", correta: true}, {texto: "Design gráfico.", correta: false}, {texto: "Comunicação multimodal.", correta: false} ], base: "Identificar desinformação e conteúdos tendenciosos, garantindo proteção e atuando na cidadania no mundo do trabalho." },
    // Preenchendo até 20 com cenários práticos
    { tipo: 3, pontos: 3, cenario: "O professor inclui a reflexão sobre o autor e o viés no plano de aula, isso significa que a educação midiática está sendo aplicada de forma:", alternativas: [{texto:"Transversal.", correta: true}, {texto:"Fragmentada.", correta: false}, {texto:"Optativa.", correta: false}], base: "A abordagem é transversal... uma camada que integra a reflexão midiática em todo o currículo." },
    { tipo: 3, pontos: 4, cenario: "Estimular o aluno a reescrever partes do texto gerado por IA para soar autêntico chama-se, segundo o protocolo:", alternativas: [{texto:"Copiar e colar.", correta: false}, {texto:"Aprimoramento humano.", correta: true}, {texto:"Engano sistêmico.", correta: false}], base: "Aprimoramento Humano: adicionar profundidade, emoção e humanizar o conteúdo gerado." },
    { tipo: 3, pontos: 2, cenario: "Discutir como um recrutador interpretaria a postagem do aluno no LinkedIn:", alternativas: [{texto:"Exercício de Inversão de papéis.", correta: true}, {texto:"Invasão de privacidade.", correta: false}, {texto:"Teste de QI.", correta: false}], base: "Exercício de inversão de papéis: analisar postagem pelo ponto de vista do recrutador." },
    { tipo: 3, pontos: 3, cenario: "Orientar sobre quando usar um mapa interativo em vez de um vídeo longo desenvolve:", alternativas: [{texto:"Fluência digital.", correta: true}, {texto:"Segurança de TI.", correta: false}, {texto:"Autoexpressão passiva.", correta: false}], base: "Explorar e escolher mídias (ferramentas) de acordo com o propósito desenvolve fluência digital." },
    { tipo: 3, pontos: 5, cenario: "O docente pede que documentem o legado de um app comunitário para garantir a manutenção do sistema a longo prazo. Fase de:", alternativas: [{texto:"Pré-produção.", correta: false}, {texto:"Avaliação do legado e engajamento cidadão.", correta: true}, {texto:"Consumo.", correta: false}], base: "Documentação do legado: registrar o impacto e propor plano de manutenção." },
    { tipo: 3, pontos: 4, cenario: "Questionar se a IA é a ferramenta certa para aquele momento do projeto faz parte de avaliar a:", alternativas: [{texto:"Intencionalidade do uso da IA.", correta: true}, {texto:"Velocidade da rede.", correta: false}, {texto:"Transparência.", correta: false}], base: "Intencionalidade: A IA é o recurso mais adequado para a minha necessidade?" },
    { tipo: 3, pontos: 2, cenario: "Ensinar a usar 2FA (Autenticação de 2 fatores) atende à habilidade de:", alternativas: [{texto:"Autoexpressão.", correta: false}, {texto:"Cidadania digital e segurança.", correta: true}, {texto:"Análise crítica.", correta: false}], base: "Checklist de segurança: O recurso de autenticação 2FA garante a segurança no perfil." },
    { tipo: 3, pontos: 3, cenario: "Refletir sobre quem tem o domínio sobre as narrativas ensina:", alternativas: [{texto:"Lógica de programação.", correta: false}, {texto:"Impacto e representação na mídia.", correta: true}, {texto:"Mídia recurso.", correta: false}], base: "Quem se beneficia? Quais vozes foram abafadas? Refletir sobre Impacto." },
    { tipo: 3, pontos: 4, cenario: "O professor questiona 'Qual o fio condutor da narrativa?' na fase de:", alternativas: [{texto:"Ativação.", correta: false}, {texto:"Imersão.", correta: false}, {texto:"Pré-produção (Planejamento).", correta: true}], base: "Pré-produção: Devem também refletir: Qual será o fio condutor da narrativa?" },
    { tipo: 3, pontos: 5, cenario: "Incentivar que os alunos usem o 'Rastreie' do método PIER para desmascarar sites falsos sobre tecnologia promove:", alternativas: [{texto:"Letramento informacional avançado.", correta: true}, {texto:"Fluência no Word.", correta: false}, {texto:"Censura governamental.", correta: false}], base: "Rastrear as alegações, citações ou mídias até a sua fonte original (Método PIER)." },
    { tipo: 3, pontos: 1, cenario: "O docente que planeja a rota de aprendizagem de mídia e de conteúdo simultaneamente age com:", alternativas: [{texto:"Intencionalidade.", correta: true}, {texto:"Improviso.", correta: false}, {texto:"Ceticismo.", correta: false}], base: "Princípio da Intencionalidade: planejar deliberadamente a rota unindo objetivos curriculares e midiáticos." },
    { tipo: 3, pontos: 2, cenario: "Discutir a diferença entre liberdade de expressão e discurso de ódio:", alternativas: [{texto:"Letramento algorítmico.", correta: false}, {texto:"Análise conceitual da cidadania digital.", correta: true}, {texto:"Avaliação de IA.", correta: false}], base: "Discurso de ódio e não-violência: analisar a fronteira entre liberdade de expressão e ódio." }
];